api_auth_login:
  path: /api/auth/login
  methods:  [POST]
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
api:
  prefix: /api
  resource: '../src/Controller'